services:
  video-drop:
    build: ./app
    container_name: video-drop
    ports:
      - "8093:8093"
    volumes:
      - ./data:/downloads
      - ./app:/code
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    environment:
      - APP_PORT=8093
      - DOWNLOAD_DIR=/downloads/finished
      - TMP_DIR=/downloads/tmp
      - MAX_CONCURRENT=3
      - BASE_URL=${server_url}
      - API_KEY=${API_KEY}
      - LIBVA_DRIVER_NAME=iHD
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4G"
    restart: unless-stopped